/**
 * CORE-006 — versioned audit action allowlist.
 * Append-only catalog; extend by bumping AUDIT_ACTION_VERSION and adding entries.
 */

export const AUDIT_ACTION_VERSION = 1 as const;

export const AUDIT_ACTIONS = [
	// AUTH — session & credential lifecycle
	'AUTH.LOGIN_SUCCESS',
	'AUTH.LOGIN_FAILED',
	'AUTH.LOGOUT',
	'AUTH.SESSION_REVOKED',
	'AUTH.PASSWORD_CHANGED',
	'AUTH.PASSWORD_RESET_REQUESTED',
	'AUTH.PASSWORD_RESET_COMPLETED',

	// TENANCY — managed tenant / room occupancy
	'TENANCY.CREATED',
	'TENANCY.UPDATED',
	'TENANCY.TERMINATED',
	'TENANCY.CHECKIN_COMPLETED',
	'TENANCY.CHECKOUT_COMPLETED',
	'TENANCY.INVITE_CREATED',
	'TENANCY.INVITE_ACCEPTED',
	'TENANCY.INVITE_REVOKED',

	// STAFF — staff profile & permissions
	'STAFF.CREATED',
	'STAFF.UPDATED',
	'STAFF.DEACTIVATED',
	'STAFF.PERMISSIONS_CHANGED',
	'STAFF.PROPERTY_SCOPE_CHANGED',

	// INVOICE — billing documents
	'INVOICE.CREATED',
	'INVOICE.DRAFT_CREATED',
	'INVOICE.UPDATED',
	'INVOICE.APPROVED',
	'INVOICE.VOIDED',
	'INVOICE.SENT',
	'INVOICE.STATUS_CHANGED',

	// PAYMENT — money movement & accounts
	'PAYMENT.RECORDED',
	'PAYMENT.ALLOCATED',
	'PAYMENT.REFUNDED',
	'PAYMENT.REVERSED',
	'PAYMENT.WAIVER_APPLIED',
	'PAYMENT.PROOF_SUBMITTED',
	'PAYMENT.PROOF_APPROVED',
	'PAYMENT.PROOF_REJECTED',
	'PAYMENT.WEBHOOK_RECEIVED',
	'PAYMENT.ACCOUNT_CONNECTED',
	'PAYMENT.ACCOUNT_DISCONNECTED',
	'PAYMENT.ACCOUNT_UPDATED',

	// DEPOSIT — tenant deposit ledger
	'DEPOSIT.RECORDED',
	'DEPOSIT.REFUNDED',
	'DEPOSIT.APPLIED',
	'DEPOSIT.FORFEITED',
	'DEPOSIT.ADJUSTED',

	// FILE — private object storage & access
	'FILE.UPLOADED',
	'FILE.DELETED',
	'FILE.VISIBILITY_CHANGED',
	'FILE.PRESIGNED_ISSUED',
	'FILE.DOWNLOAD_AUTHORIZED',

	// JOB — background / automation runs
	'JOB.QUEUED',
	'JOB.STARTED',
	'JOB.COMPLETED',
	'JOB.FAILED',
	'JOB.RETRIED',
	'JOB.CANCELLED',
	'JOB.MANUAL_DISPATCH',

	// CONFIG — landlord-scoped settings
	'CONFIG.UPDATED',
	'CONFIG.PAYMENT_ACCOUNT_CREATED',
	'CONFIG.PAYMENT_ACCOUNT_UPDATED',
	'CONFIG.PAYMENT_ACCOUNT_DEACTIVATED',
	'CONFIG.SUBSCRIPTION_REQUESTED',
	'CONFIG.SUBSCRIPTION_APPROVED',

	// PLATFORM — super-admin / cross-tenant operations
	'PLATFORM.LANDLORD_CREATED',
	'PLATFORM.LANDLORD_UPDATED',
	'PLATFORM.LANDLORD_ACTIVATED',
	'PLATFORM.LANDLORD_DEACTIVATED',
	'PLATFORM.USER_CREATED',
	'PLATFORM.USER_ACTIVATED',
	'PLATFORM.USER_DEACTIVATED',
	'PLATFORM.BACKFILL_EXECUTED'
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export function isAuditAction(value: string): value is AuditAction {
	return (AUDIT_ACTIONS as readonly string[]).includes(value);
}
